image:
  file: gitpod-qemu.dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: qemu
    init: ./build-examples.sh
    command: ./run-example 09
